language: python

install:
 - pip install --upgrade pip setuptools
 - pip install tox

script:
  - tox

after_success:
  - source .tox/${TOXENV}/bin/activate && pip install codecov && codecov --env CI,TRAVIS_OS_NAME,TOXENV

env:
  global:
    - PYTHONWARNINGS=always::DeprecationWarning
matrix:
  include:
    - python: "3.6"
      env: TOXENV=py36
    - python: "3.6"
      env: TOXENV=docs
    - python: "3.6"
      env: TOXENV=lint
