---
- name: Install database packages
  package:
      name: "{{ item }}"
      state: present
  with_items:
      - rabbitmq-server

- name: enable plugins
  copy: src=rabbitmq_plugins dest=/etc/rabbitmq/enabled_plugins owner=root group=root mode=0644

- name: start rabbitmq
  service: name=rabbitmq-server state=started enabled=yes
